service: recipe-book

image: enzopalavicino/recipe-book # Ajusta si cambias el repositorio en Docker Hub

servers:
  - 138.68.22.139 # IP pública del droplet de producción

ssh:
  user: root

registry:
  username: enzopalavicino
  password:
    - DOCKER_HUB_ACCESS_TOKEN

env:
  clear:
    RAILS_ENV: production
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL # Define la URL real en .kamal/secrets

builder:
  arch: amd64
